"""add order index in assignment

Revision ID: 333346518469
Revises: c63fc29bf0f9
Create Date: 2026-07-09 09:11:17.058267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '333346518469'
down_revision = 'c63fc29bf0f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_index', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_column('order_index')

    # ### end Alembic commands ###
