"""update certificates table

Revision ID: 38b3b66f6f7d
Revises: 3c1f4f6b2a91
Create Date: 2026-07-08 08:49:04.034891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38b3b66f6f7d'
down_revision = '3c1f4f6b2a91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
