"""course date and fee model update

Revision ID: 41d1d02aa52e
Revises: 6485d83da432
Create Date: 2026-09-22 11:08:30.914200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41d1d02aa52e'
down_revision = '6485d83da432'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_term', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('term_start_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('term_end_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('amount_paid', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('refund_status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.drop_column('refund_status')
        batch_op.drop_column('amount_paid')
        batch_op.drop_column('term_end_date')
        batch_op.drop_column('term_start_date')
        batch_op.drop_column('course_term')

    # ### end Alembic commands ###
