"""added active status column

Revision ID: 6485d83da432
Revises: bacadd835e04
Create Date: 2026-07-19 18:04:29.756811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6485d83da432'
down_revision = 'bacadd835e04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active_status', sa.Boolean(), nullable=True))

    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active_status', sa.Boolean(), nullable=True))

    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active_status', sa.Boolean(), nullable=True))

    with op.batch_alter_table('weeks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active_status', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weeks', schema=None) as batch_op:
        batch_op.drop_column('active_status')

    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_column('active_status')

    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_column('active_status')

    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_column('active_status')

    # ### end Alembic commands ###
