"""update certificates table remove qr url

Revision ID: a6899968643f
Revises: b6c8f9ffce00
Create Date: 2026-07-08 10:18:31.421067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6899968643f'
down_revision = 'b6c8f9ffce00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.drop_column('qrcode_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qrcode_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
