"""fix ambiguous foreign keys

Revision ID: a6c36f09f0d9
Revises: 333346518469
Create Date: 2026-07-09 11:25:29.370311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6c36f09f0d9'
down_revision = '333346518469'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignment_submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_possible', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('percentage', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('is_graded', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('graded_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('graded_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['graded_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignment_submissions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('graded_by')
        batch_op.drop_column('graded_at')
        batch_op.drop_column('is_graded')
        batch_op.drop_column('percentage')
        batch_op.drop_column('total_possible')
        batch_op.drop_column('score')

    # ### end Alembic commands ###
