"""update certificates table

Revision ID: b6c8f9ffce00
Revises: 38b3b66f6f7d
Create Date: 2026-07-08 10:15:28.162290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6c8f9ffce00'
down_revision = '38b3b66f6f7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_token', sa.String(length=100), nullable=False))
        batch_op.create_unique_constraint(None, ['verification_token'])
        batch_op.drop_column('certificate_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('certificate_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('verification_token')

    # ### end Alembic commands ###
