"""update model

Revision ID: bacadd835e04
Revises: a6c36f09f0d9
Create Date: 2026-07-09 12:27:37.021461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bacadd835e04'
down_revision = 'a6c36f09f0d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_answers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('marks_obtained', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_answers', schema=None) as batch_op:
        batch_op.drop_column('marks_obtained')

    # ### end Alembic commands ###
