"""update certificates table readd course_code column

Revision ID: c63fc29bf0f9
Revises: a6899968643f
Create Date: 2026-07-08 10:55:48.993669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c63fc29bf0f9'
down_revision = 'a6899968643f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_code', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.drop_column('course_code')

    # ### end Alembic commands ###
